from fastapi import Request, HTTPException, Depends
# from app.database.db import sessionLocal
from app.database.db import async_session_maker
from typing import Any
from app.services.api_permission_regis_service import check_permission
from app.services.rbac_auth_services import EnterpriseAuthorizationService
from app.api.deps import get_auth_enforcer
from app.utils.logger_config import logger

async def check_permissions_middleware(request: Request, call_next, enforcer: EnterpriseAuthorizationService = Depends(get_auth_enforcer)) -> Any:
    """
    TLDR:  This middleware verifies that the incoming request has the necessary permissions.
    Args:
        request (Request): The incoming HTTP request object.
        call_next (Callable): The next middleware or route handler in the chain.
        enforcer (EnterpriseAuthorizationService): Authorization service instance,
            injected as a dependency to perform permission checks.

    Returns:
        Any: The response object generated by the next middleware or route handler.

    Raises:
        HTTPException: If the permission check fails.

    Side Effects:
        - Logs permission check status for each request.
        - Ensures the database session is properly closed after processing
    """
    async with async_session_maker() as db:
        try:
            await check_permission(request, db, enforcer)
            logger.info(f"Permissions checked for request: {request.method} {request.url}")
            response = await call_next(request)
            return response
        finally:
            await db.close()